name: Check

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y libarchive13 libarchive-dev

      - name: Configure Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Tox
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install tox

      - name: Run Linter (3.9)
        run: |
          tox -e py39-lint

      - name: Run Tests (3.9)
        run: |
          tox -e py39-test

      - name: Configure Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Tox
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install tox

      - name: Run Linter (3.8)
        run: |
          tox -e py38-lint

      - name: Run Tests (3.8)
        run: |
          tox -e py38-test
